import express from 'express';
import { getCart, addToCart, updateCartItem, removeFromCart } from '../controllers/cartController.js';
import { protect } from '../middlewares/auth.js';
const router = express.Router();
router.use(protect);
router.get('/', getCart);
router.post('/', addToCart);
router.put('/', updateCartItem);
router.delete('/:itemId', removeFromCart);
export default router;